CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=70
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=7
CONFIG_RGBLED_WIDGET_CONN_COLOR_DISCONNECTED=5
CONFIG_RGBLED_WIDGET=y
CONFIG_USB_DEVICE_PRODUCT="keyboardK"
CONFIG_BT_MAX_PAIRED=1
CONFIG_BT_MAX_CONN=1
